name = "airbeat"
compatibility_date = "2025-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "airbeat-db"
database_id = "366c021e-77b9-481b-84dd-5ed94990f606"
