name = "airbeat-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "airbeat"
database_id = "376218c5-cfde-4de9-a8bd-f8902d98fd54"

[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "airbeat-audio"

[[kv_namespaces]]
binding = "CACHE"
id = "9b1cfe3ed757459ebb57ef7b8155c057"

[vars]
OPENROUTER_MODEL = "google/gemma-4-26b-a4b-it:free"
